fix: MagicOnionClientSourceGeneration Compile error
MagicOnion.Client.SourceGenerator.Unity\MagicOnion.Client.SourceGenerator.MagicOnionClientSourceGenerator\アプリ名_Unity_MagicOnionClientInitializer_MessagePack.g.cs(62,73): error CS0234: The type or namespace name 'MessagePack' does not exist in the namespace 'MagicOnion.Serialization' (are you missing an assembly reference?)